// Page content for GoalTally. Each page: slug, title, desc, h1, lead, tool, body, faq (+ howto on the home page).
const tbl = (head, rows) => `      <table><thead><tr>${head.map(h => `<th>${h}</th>`).join("")}</tr></thead><tbody>
${rows.map(r => `      <tr>${r.map(c => `<td>${c}</td>`).join("")}</tr>`).join("\n")}
      </tbody></table>`;
const steps = items => `      <ol class="steps">\n${items.map(([b, t]) => `        <li><strong>${b}</strong> ${t}</li>`).join("\n")}\n      </ol>`;
const ul = items => `      <ul>\n${items.map(t => `        <li>${t}</li>`).join("\n")}\n      </ul>`;
const quick = t => `      <p class="tldr"><strong>Quick answer:</strong> ${t}</p>`;
const h2 = (t, id) => `      <h2${id ? ` id="${id}"` : ""}>${t}</h2>`;
const p = t => `      <p>${t}</p>`;
const typegrid = items => `      <div class="typegrid">\n${items.map(([h, b, s]) => `        <a href="${h}"><b>${b}</b><span>${s}</span></a>`).join("\n")}\n      </div>`;
const ALL_SHEETS = [
  ["/trial-by-trial-data-sheet", "Trial-by-trial (DTT)", "+ / – for every trial, with % correct per session."],
  ["/prompt-level-data-sheet", "Prompt level", "Circle FP, PP, M, G, V or I on each trial."],
  ["/cold-probe-data-sheet", "Cold probe", "Y / N on the first trial of the day for many targets."],
  ["/task-analysis-data-sheet", "Task analysis", "Score each step of a routine; % of steps independent."],
  ["/frequency-data-sheet", "Frequency and rate", "Tally each occurrence; convert to rate per hour."],
  ["/duration-recording-data-sheet", "Duration and latency", "Episode start and stop times, totals and % of time."],
  ["/partial-interval-recording-data-sheet", "Partial interval", "Mark if the behavior happened at any time in the interval."],
  ["/whole-interval-recording-data-sheet", "Whole interval", "Mark only if it lasted the entire interval."],
  ["/momentary-time-sampling-data-sheet", "Momentary time sampling", "Look up at the end of each interval and mark."],
  ["/abc-data-sheet", "ABC (antecedent-behavior-consequence)", "Checklist or narrative incident log for FBAs."],
];

export const PAGES = [
  /* ------------------------------------------------------------------ HOME */
  {
    slug: "", tool: { kind: "graph", preset: "ab" },
    title: "ABA Graph Maker: Free Phase Change Line Graphs | GoalTally",
    desc: "Free ABA graph maker with phase change lines, broken data paths, condition labels, aim and trend lines and a mastery check. PNG or PDF, no signup, no uploads.",
    h1: "Free ABA Graph Maker",
    lead: "Type or paste session data and get a clean single-case line graph with phase-change lines, condition labels, an aim line, a trend line and a mastery check. Download it as PNG or PDF.",
    howto: { name: "How to make an ABA graph", time: "PT3M", steps: [
      ["Name the graph", "Add the student's initials, the target behavior or skill, and the y-axis label, such as Percent correct or Rate per hour."],
      ["Enter session data", "Type one value per session, with an optional date, or paste columns from Excel or Google Sheets."],
      ["Mark phase changes", "Add a phase for each condition, such as Baseline and Intervention, and set the session where it starts. The data path breaks at each phase-change line."],
      ["Add lines", "Turn on a least-squares or split-middle trend line, an aim line from baseline to the goal, and a mastery criterion."],
      ["Download", "Download a PNG for reports and slides, or a PDF with a phase summary table and a progress note."]] },
    body: [
      quick("To make an ABA graph, enter one data point per session and start a new phase wherever the condition changed (for example, baseline to intervention). The graph maker draws a dashed phase-change line, breaks the data path between phases and labels each condition. Turn on a least-squares or split-middle trend line, an aim line and a mastery criterion if you need them, then download a PNG for a report or a PDF with a phase summary."),
      h2("How to make an ABA graph in 5 steps", "how"),
      steps([
        ["Name the graph.", "Add the student's initials (not their name), the target behavior or skill, and the y-axis label, such as <em>Percent correct</em> or <em>Rate per hour</em>."],
        ["Enter your data.", "One row per session, with an optional date. Press Enter to jump to the next session, or paste columns straight from Excel or Google Sheets."],
        ["Mark phase changes.", "Add a phase for each condition (Baseline, Intervention, Maintenance) and set the session where it starts. The data path breaks at every phase-change line."],
        ["Add lines.", "Turn on a trend line (least squares or split-middle), an aim line from baseline to the goal, and a mastery criterion such as 80% for 3 consecutive sessions."],
        ["Download.", "Get a 2000 × 1240 px PNG for slides and reports, or a vector PDF with a summary table and an editable progress note."],
      ]),
      h2("What a standard ABA line graph includes"),
      p("Behavior analysts follow shared visual conventions so that anyone can read a graph quickly and judge whether behavior changed when the condition changed. GoalTally applies them by default:"),
      tbl(["Element", "Convention", "In GoalTally"], [
        ["Axes", "Sessions or dates along the x-axis; the measure (percent, count, rate, duration) up the y-axis.", "Session numbers or a true calendar axis, with any y-axis label."],
        ["Data points and path", "One marker per session, joined by straight lines within a phase.", "Filled circles, with open squares and triangles for a second and third series."],
        ["Phase-change lines", "A vertical dashed line between the last session of one condition and the first session of the next.", "Drawn halfway between the two sessions."],
        ["Broken data path", "Points are never connected across a phase-change line.", "Automatic. Missed sessions also break the line unless you choose to connect them."],
        ["Condition labels", "A short name centered above each phase.", "Taken from your phase names; long names wrap onto two lines."],
        ["Floating zero", "Zero sits slightly above the x-axis so zero values stay visible.", "On whenever the y-axis starts at 0."],
        ["No chart junk", "No gridlines, 3-D effects or background shading.", "Black-and-white style by default; a color style is optional."],
      ]),
      h2("Trend lines: least squares or split-middle?"),
      p("A trend line summarizes the direction and steepness of the data within one phase. GoalTally draws one per phase, on the first data series, once a phase has at least 3 data points, and the legend names the method used."),
      tbl(["Method", "How it's calculated", "When to use it"], [
        ["Least squares (ordinary least-squares regression)", "The straight line with the smallest total squared vertical distance to all the points in the phase.", "A good default for reports. It uses every data point, so one extreme value can pull it."],
        ["Split-middle (White's line of progress)", "Split the phase in half by session, join the median session and median value of each half, then slide the line up or down, keeping its slope, until half the points fall on or above it and half on or below.", "Resistant to outliers, and the method many behavior-analytic courses teach for visual analysis."],
      ]),
      p("With an odd number of points, the middle point is left out when the two halves are formed and counted again when the line is shifted. The summary table under the graph always reports the least-squares slope per session (or per week on a date axis), so you have a number to quote."),
      h2("Aim lines and mastery criteria"),
      p("An aim line, also called a goal line, joins the student's starting level to the goal by the target session or date, so you can see at a glance whether progress is fast enough. Click <em>Start at the baseline median</em> to begin the line at the median of the baseline phase, then enter the goal value and when it should be reached."),
      p("The mastery check reads your criterion, for example at or above 80% on 3 consecutive sessions or at or below 2 incidents for 5 sessions, and reports the first session where it was met. Sessions without data are skipped rather than counted as failures. The summary also lists each phase's mean, median, range, trend and PND (the percentage of non-overlapping data compared with the phase before)."),
      h2("Reading the graph: six things to compare"),
      p("Visual analysis compares adjacent phases on six features:"),
      ul([
        "<strong>Level:</strong> how high or low the data sit (the phase mean or median).",
        "<strong>Trend:</strong> the direction and steepness of change within the phase.",
        "<strong>Variability:</strong> how much the points bounce around the trend.",
        "<strong>Immediacy:</strong> how quickly behavior changes after the phase change.",
        "<strong>Overlap:</strong> how many points in one phase fall within the range of the other.",
        "<strong>Consistency:</strong> whether similar phases (for example, both baselines in an ABAB design) look alike.",
      ]),
      p("The summary table gives you numbers for level, trend and overlap. Variability and immediacy are easiest to judge by eye on the graph itself."),
      h2("Data sheets for every measurement type"),
      p("Collect the data, then graph it. GoalTally also makes printable data sheets, and you can score a session on a tablet and send it straight to the goal's graph."),
      typegrid(ALL_SHEETS),
      h2("Private by design"),
      p("Everything happens in your browser. Graphs, sheets and saved goals are kept in this browser's storage on your device and never uploaded, so we can't see them. Use initials rather than names, and download an encrypted backup (under <em>Backup, restore &amp; export</em>) before clearing browser data or switching devices. GoalTally is a free tool, not a records system, so follow your school's or clinic's data policies too."),
    ].join("\n"),
    faq: [
      ["Is this ABA graph maker free?", "Yes. Every feature is free with no account: unlimited graphs, PNG and PDF downloads, saved goals, data sheets, on-screen scoring and backups. A small “Made with GoalTally” credit appears under exported graphs."],
      ["How do I add a phase change line?", "Click <em>Add phase change</em>, name the new condition and set the session where it starts. The dashed line is drawn halfway between the last session of the old phase and the first session of the new one, and the data path breaks there."],
      ["Can I graph two data paths, such as independent and prompted responses?", "Yes. Choose 2 or 3 series. Each gets its own marker (filled circle, open square, filled triangle) and a legend entry. Trend lines, the aim line and the mastery check use the first series."],
      ["Can I paste data from Excel or Google Sheets?", "Yes. Copy the cells and paste them into <em>Paste from Excel or Google Sheets</em>. It reads a header row (Session, Date, Phase, Value), the one-column-per-phase layout many Excel templates use, phase names on their own lines, or a plain list of numbers."],
      ["Does it work for IEP progress monitoring?", "Yes. Switch the x-axis to calendar dates, add an aim line from baseline to the annual goal, and use the progress note as a starting point for your report. The <a href=\"/iep-progress-monitoring-graph\">IEP progress monitoring graph</a> page has a worked example."],
      ["Where is my data stored?", "Only in your browser on this device. Nothing is uploaded. Saved goals stay until you delete them or clear your browser data, so download an encrypted backup regularly."],
      ["Can I use the graphs for a BCBA course assignment or a report?", "Yes, the PNG and PDF are yours to use. Check your course's or employer's graphing requirements, since some ask for a specific axis range, font or figure caption."],
    ],
  },

  /* ------------------------------------------------------------------ HUB */
  {
    slug: "iep-data-sheet-generator", tool: { kind: "sheet", preset: "trial" }, crumb: "IEP data sheet generator",
    title: "IEP Data Sheet Generator: Free Printable ABA Data Sheets",
    desc: "Printable data sheets for any IEP goal: trial-by-trial, prompt level, cold probe, task analysis, frequency, duration, interval or ABC. Free PDF, no signup.",
    h1: "IEP Data Sheet Generator",
    lead: "Pick how the goal is measured, set the trials, steps or intervals, and download a matching PDF data sheet. Score sessions on a tablet and they're graphed for you.",
    body: [
      quick("Choose the measurement type that matches the goal's wording, add the student's initials and the goal, adjust the trials, sessions, steps or interval length, then download the PDF or print. Every sheet is free and unlimited. To track progress, save the goal and use <em>Score a session on screen</em>: each session becomes a point on the goal's graph and can be filled into the printed sheet."),
      h2("Which data sheet fits the goal?"),
      p("The wording of the goal usually tells you how it should be measured. Match the criterion to the sheet:"),
      tbl(["If the goal says…", "You're measuring", "Use this sheet"], [
        ["“…in 8 of 10 trials” or “…with 80% accuracy”", "Percent correct per session", "<a href=\"/trial-by-trial-data-sheet\">Trial-by-trial</a>"],
        ["“…independently” or “…with no more than a gestural prompt”", "The level of help on each trial", "<a href=\"/prompt-level-data-sheet\">Prompt level</a>"],
        ["“…will identify 20 sight words” or “…across 3 consecutive probes”", "Targets correct on the first try", "<a href=\"/cold-probe-data-sheet\">Cold probe</a>"],
        ["“…will complete all steps of handwashing”", "Percent of steps done independently", "<a href=\"/task-analysis-data-sheet\">Task analysis</a>"],
        ["“…will call out fewer than 3 times per lesson”", "Count or rate", "<a href=\"/frequency-data-sheet\">Frequency</a>"],
        ["“…tantrums will last under 2 minutes” or “…will stay seated for 10 minutes”", "Time", "<a href=\"/duration-recording-data-sheet\">Duration</a>"],
        ["“…will begin work within 30 seconds of the instruction”", "Seconds until the response starts", "Latency (on the <a href=\"/duration-recording-data-sheet\">duration</a> page)"],
        ["“…will be on task during 80% of intervals”", "Percent of intervals", "<a href=\"/whole-interval-recording-data-sheet\">Whole interval</a> or <a href=\"/momentary-time-sampling-data-sheet\">momentary time sampling</a>"],
        ["“…will reduce off-task behavior” (brief or hard-to-count behavior)", "Percent of intervals", "<a href=\"/partial-interval-recording-data-sheet\">Partial interval</a>"],
        ["A behavior plan or FBA asks “why does it happen?”", "What comes before and after", "<a href=\"/abc-data-sheet\">ABC</a>"],
      ]),
      h2("How to set up a data sheet"),
      steps([
        ["Choose the measurement type.", "The options below it change to match: trials and sessions, prompt codes, targets, steps, behaviors or interval length."],
        ["Add initials and the target.", "Use initials only. Paste the goal or objective and the mastery criterion so whoever collects data knows what counts."],
        ["Adjust the layout.", "Set the number of trials, date columns, steps, targets, episode boxes or the interval length. The preview updates as you type."],
        ["Download or print.", "US Letter or A4, portrait or landscape. Long sheets continue onto more pages with the column headers repeated."],
        ["Save the goal (optional).", "Saved goals stay on this device. Open <em>Backup, restore, print all &amp; export</em> to print every sheet for one student in a single PDF."],
      ]),
      h2("Scoring on a tablet or phone"),
      p("<em>Score a session on screen</em> opens a tap-friendly version of the sheet: tap + or – for each trial, tap prompt codes, count with a big +1 button, time episodes with a stopwatch, or run an interval timer that beeps at each interval. Save the session and GoalTally works out the percentage or rate, adds it to the goal's graph, and can fill it into the printed sheet, including the totals and percentage rows."),
      h2("All data sheet types"),
      typegrid(ALL_SHEETS),
      h2("Tips for data you can trust"),
      ul([
        "<strong>Define the behavior or response</strong> in observable words, so two people would score the same session the same way.",
        "<strong>Decide when data is taken:</strong> every trial, the first trial of the day (a probe), or a set observation period. Keep it the same from session to session.",
        "<strong>Keep the sheet with the materials</strong> and score straight away. Data written from memory at the end of the day is less accurate.",
        "<strong>Graph at least weekly.</strong> Patterns are much easier to see on a graph than in columns of numbers.",
        "<strong>Check agreement now and then.</strong> Have a second person score the same session independently. For trial data, agreement = agreements ÷ (agreements + disagreements) × 100.",
      ]),
    ].join("\n"),
    faq: [
      ["Are the data sheets really free?", "Yes. Every measurement type, unlimited PDFs, printing, saved goals, on-screen scoring and bulk printing are free with no account. Each sheet carries a small “Made with GoalTally” credit in the footer."],
      ["Can I change the prompt hierarchy?", "Yes. On prompt level and task analysis sheets, edit the hierarchy list, one code per line in the form <em>FP = Full physical</em>. The code labeled Independent (or I) is the one counted for % independent."],
      ["Can I add my school or clinic logo?", "Yes. Upload a PNG or JPG under Page. It's stored only in this browser and printed at the top right of every sheet."],
      ["Can I print all goals for one student at once?", "Yes. Save each goal with the same student initials, then open <em>Backup, restore, print all &amp; export</em>, choose the student and download one PDF with every sheet."],
      ["Is this IEP data sheet generator FERPA or HIPAA compliant?", "GoalTally doesn't receive, store or transmit student information: everything stays in your browser. It makes no compliance claims, because that depends on how your organization handles devices and printed sheets. Use initials and follow your district or clinic policy."],
    ],
  },

  /* ------------------------------------------------------------------ TRIAL */
  {
    slug: "trial-by-trial-data-sheet", tool: { kind: "sheet", preset: "trial" }, crumb: "Trial-by-trial data sheet",
    title: "Trial by Trial Data Sheet: Free Printable DTT Template",
    desc: "Free trial by trial data sheet for discrete trial teaching: 1–40 trials, up to 31 date columns, + / – codes and a % correct row. Print it or download a PDF.",
    h1: "Trial-by-Trial Data Sheet",
    lead: "A discrete trial teaching (DTT) sheet with one row per trial and one column per session. Choose the number of trials and dates, print it, or score on a tablet and get % correct automatically.",
    body: [
      quick("A trial-by-trial data sheet records the outcome of every learning trial in a session, usually + for a correct, independent response and – for an incorrect, prompted or missing one. At the end of the session, % correct = number of + ÷ number of trials run × 100. That percentage is the number you graph."),
      h2("How to fill in a trial-by-trial data sheet"),
      steps([
        ["Write the date", "at the top of the column before the session starts."],
        ["Present the instruction", "(the discriminative stimulus, or SD) and wait for the response."],
        ["Circle + or –.", "+ if the student responded correctly without help; – if they responded incorrectly, didn't respond, or needed a prompt. To track prompted trials separately, switch the codes to + / P / –."],
        ["Total the column.", "After the last trial, write the number of + marks and the % correct in the rows at the bottom."],
        ["Graph the percentage.", "With on-screen scoring, the totals and the graph point are filled in for you."],
      ]),
      h2("Worked example"),
      p("Ten trials of “Touch red” across three sessions:"),
      tbl(["Session", "Correct (+)", "Trials run", "% correct"], [
        ["1", "6", "10", "60%"],
        ["2", "7", "10", "70%"],
        ["3", "6", "8 (session ended early)", "75%"],
      ]),
      p("Session 3 shows why the percentage uses trials actually run: 6 of 8 is 75%, not 60%."),
      h2("Every trial, or first trial only?"),
      p("Recording every trial gives the most detail and shows learning within a session. Many programs record only the first trial of each target per session instead, because it's fast and a strict test of what the learner can do without help. For that approach, use the <a href=\"/cold-probe-data-sheet\">cold probe data sheet</a>. Whichever you choose, keep it consistent so sessions can be compared."),
      h2("Choosing a mastery criterion"),
      p("The BCBA or IEP team sets the criterion. Common examples are 80% or 90% correct across 2 or 3 consecutive sessions, sometimes with a different staff member or setting to check that the skill generalizes. Write the criterion on the sheet so everyone knows when to move on, and use the mastery check in the <a href=\"/\">ABA graph maker</a> to see when it's been met."),
      h2("Tips"),
      ul([
        "Score straight after each trial rather than from memory at the end.",
        "Keep the number of trials similar across sessions where you can. If it varies, % correct still compares fairly.",
        "Follow your program's rules for error-correction trials. Most don't count them as new trials.",
        "Use the notes box for anything that might explain the data: a new reinforcer, a substitute teacher, a short session.",
      ]),
    ].join("\n"),
    faq: [
      ["How do you calculate percent correct on a trial-by-trial data sheet?", "Divide the number of correct trials by the number of trials actually run and multiply by 100. 7 correct out of 10 trials is 70%. If only 8 trials were run and 6 were correct, it's 6 ÷ 8 = 75%."],
      ["Should a prompted response count as correct?", "Usually not, when the measure is independent correct responding. Score it as – or use the + / P / – codes so prompted trials are visible but not counted as correct."],
      ["How many trials should a session have?", "It depends on the learner and the program. Sessions of 5 to 20 trials per target are common. The sheet supports 1 to 40 trials."],
      ["Can I fit more sessions on one sheet?", "Yes. Each column is a session. Choose up to 31 columns; the sheet switches to landscape automatically when the columns need more room."],
    ],
  },

  /* ------------------------------------------------------------------ PROMPT */
  {
    slug: "prompt-level-data-sheet", tool: { kind: "sheet", preset: "prompt" }, crumb: "Prompt level data sheet",
    title: "Prompt Level Data Sheet: Free Printable with Prompt Codes",
    desc: "Free prompt level data sheet: circle FP, PP, M, G, V or I on each trial, edit the prompt hierarchy and get % independent per session. Print or download a PDF.",
    h1: "Prompt Level Data Sheet",
    lead: "Record how much help each trial needed, from full physical to independent. Edit the prompt codes to match your hierarchy, print the sheet, or tap codes on a tablet.",
    body: [
      quick("A prompt level data sheet records the level of prompting a learner needed on each trial, using codes such as FP (full physical), PP (partial physical), M (model), G (gestural), V (verbal) and I (independent). The usual summary is % independent: trials scored I ÷ trials run × 100. Codes moving toward I across sessions show that prompts are being faded."),
      h2("Common prompt codes"),
      tbl(["Code", "Prompt", "What it looks like"], [
        ["FP", "Full physical", "Hand-over-hand guidance through the whole response."],
        ["PP", "Partial physical", "A light touch or nudge, for example at the elbow or wrist."],
        ["M", "Model", "You demonstrate the response for the learner to imitate."],
        ["G", "Gestural", "Pointing, nodding or looking toward the correct answer."],
        ["V", "Verbal", "A spoken hint or part of the answer (“It starts with b…”)."],
        ["I", "Independent", "A correct response with no prompt after the instruction."],
      ]),
      p("Some teams add visual prompts (a picture or written cue) or positional prompts (placing the correct item closer to the learner). Add them to the hierarchy in the sheet options. Whatever code you label <em>Independent</em> is the one counted."),
      h2("Most-to-least or least-to-most?"),
      p("<strong>Most-to-least</strong> prompting starts with the most supportive prompt and fades to less help as the learner succeeds. It's often used for new skills to keep errors low. <strong>Least-to-most</strong> prompting starts by waiting for an independent response and adds help only when needed, so the learner gets a chance to respond independently on every trial. The sheet works for both: list the codes in the order your team uses them."),
      h2("How to use the sheet"),
      steps([
        ["Set the layout.", "Choose trials per session and how many sessions (date columns) the sheet holds."],
        ["Check the hierarchy.", "Edit the list if your program uses different codes or more levels."],
        ["Circle one code per trial:", "the level of help the learner needed to respond correctly."],
        ["Total the session.", "Count the I's and write # independent and % independent at the bottom of the column."],
        ["Graph % independent.", "Or score on screen and the graph point is added for you."],
      ]),
      h2("Graphing prompt level data"),
      p("% independent is the simplest line to graph. Some teams also graph the prompt level itself as a number, for example FP = 0 up to I = 5, to show fading before independence appears. If you do that, fix the numbers in advance and label the y-axis clearly. You can enter either kind of value in the <a href=\"/\">ABA graph maker</a>, and use two data series to show both on one graph."),
    ].join("\n"),
    faq: [
      ["What is a prompt hierarchy?", "An ordered list of prompts from most to least support (or the reverse), such as full physical, partial physical, model, gestural, verbal, independent. It tells staff which prompt to try next so help can be faded systematically."],
      ["Can I change the prompt codes?", "Yes. Edit the hierarchy box, one code per line as <em>code = meaning</em>. The codes print in every box and appear as tap buttons when you score on screen."],
      ["What if the learner is wrong even with a prompt?", "Record the most supportive prompt you gave and follow your program's error-correction procedure. Only independent correct responses count toward % independent."],
      ["How is % independent calculated?", "Trials scored I ÷ trials run × 100. 4 independent trials out of 10 is 40%."],
    ],
  },

  /* ------------------------------------------------------------------ PROBE */
  {
    slug: "cold-probe-data-sheet", tool: { kind: "sheet", preset: "probe" }, crumb: "Cold probe data sheet",
    title: "Cold Probe Data Sheet: Free Printable Template (PDF)",
    desc: "Free cold probe data sheet: list targets, mark Y or N on the first trial each day, and track date introduced and date mastered. Print, PDF or score on screen.",
    h1: "Cold Probe Data Sheet",
    lead: "List the targets, probe each one once at the start of the session, and circle Y or N. Track when each target was introduced and mastered, all on one page.",
    body: [
      quick("Cold probe data records whether the learner gets each target right on the first opportunity of the day, before any teaching or prompting. That's what “cold” means. Mark Y for a correct, unprompted first response and N for anything else. A target is usually counted as mastered after a set number of consecutive Y probes, such as 3 days in a row, and then moved to maintenance."),
      h2("Why probe instead of recording every trial?"),
      p("A probe takes a few seconds per target, so one sheet can track 10, 20 or more targets at once and teaching time isn't spent writing. Because the probe comes before any help that day, a Y is a strict test of what the learner can do independently. The trade-off is detail: you won't see progress within a session. Many programs use both, with cold probes for mastery decisions and <a href=\"/trial-by-trial-data-sheet\">trial-by-trial data</a> for new or difficult targets."),
      h2("How to run and record a cold probe"),
      steps([
        ["Probe before teaching.", "Present each target once, the same way every day, before any practice on it."],
        ["Give no prompts.", "Wait a set time for a response, for example 3 to 5 seconds."],
        ["Circle Y or N.", "Y if correct and independent; N if incorrect, no response, or a prompt was needed."],
        ["Then teach as planned.", "Teaching trials aren't recorded on the probe sheet."],
        ["Record mastery.", "When a target meets the criterion, write the date in <em>Date mastered</em> and add a new target."],
      ]),
      h2("Example"),
      p("With a criterion of 3 consecutive Y probes:"),
      tbl(["Target", "Mon", "Tue", "Wed", "Thu", "Date mastered"], [
        ["Dog", "N", "Y", "Y", "Y", "Thu"],
        ["Ball", "Y", "Y", "Y", "", "Wed"],
        ["Cup", "N", "N", "Y", "N", "Not yet (the run restarts)"],
      ]),
      h2("Graphing cold probe data"),
      p("Two graphs are common. The first is the <strong>percentage of targets correct</strong> each day (Y ÷ targets probed × 100); on-screen scoring adds this point to the goal's graph automatically. The second is a <strong>cumulative graph of targets mastered</strong>, where the line steps up by one each time a target meets the criterion. For that one, enter the running total in the <a href=\"/\">graph maker</a> and label the y-axis “Number of targets mastered”."),
    ].join("\n"),
    faq: [
      ["What does “cold” mean in a cold probe?", "The first opportunity of the day, before any teaching, prompting or warm-up on that target. It tests what the learner can do on their own."],
      ["How many consecutive Y probes count as mastered?", "Your team decides. Common criteria are 2 or 3 consecutive sessions, sometimes across two different staff members. Write it in the mastery criterion box so it prints on the sheet."],
      ["How many targets fit on one sheet?", "About 20 on a portrait page with the default layout. Longer lists continue onto more pages, with the column headers repeated."],
      ["Can I probe on a tablet?", "Yes. Use <em>Score a session on screen</em>, tap Y or N for each target, and save. The day's percentage goes onto the goal's graph and can be filled into the printed sheet."],
    ],
  },

  /* ------------------------------------------------------------------ TASK */
  {
    slug: "task-analysis-data-sheet", tool: { kind: "sheet", preset: "task" }, crumb: "Task analysis data sheet",
    title: "Task Analysis Data Sheet Template: Free Printable PDF",
    desc: "Free task analysis data sheet template: list each step, score prompt levels or + / – each session and track % of steps independent for chaining. Print or PDF.",
    h1: "Task Analysis Data Sheet Template",
    lead: "Break a routine into steps, score each step every session and track the percentage done independently. Works for forward, backward and total-task chaining.",
    body: [
      quick("A task analysis data sheet lists every step of a multi-step skill, such as handwashing or packing a school bag, in order, with a column for each session. For each step you record the help needed (a prompt level or + / –), then calculate % of steps independent = steps done independently ÷ steps scored × 100."),
      h2("Writing the task analysis"),
      ul([
        "Watch a competent person do the task, or do it yourself, and write each step as an observable action: “Turn on the water”, not “Get ready”.",
        "Make the steps small enough for the learner to learn one at a time. A learner who needs more support may need more, smaller steps.",
        "Put the steps in the order they'll be taught and check the list by having someone follow it exactly.",
        "Use the same list every session so the percentages are comparable. Edit the steps in the sheet options above.",
      ]),
      h2("Forward, backward or total-task chaining"),
      tbl(["Method", "What you teach", "Often a good fit when"], [
        ["Forward chaining", "The first step is taught to mastery while you help with the rest; then the first two steps, and so on.", "The early steps are the easiest or the learner does well starting at the beginning."],
        ["Backward chaining", "You complete every step except the last, which the learner does; then the last two, and so on.", "Finishing the task right away (and getting the natural reward) helps motivation."],
        ["Total task", "Every step, every session, with prompts as needed on each one.", "The learner can already do some steps, or the task is short."],
      ]),
      h2("How to score the sheet"),
      steps([
        ["Enter the steps,", "one per line. The sheet numbers them for you."],
        ["Choose the scoring:", "prompt levels (FP, PP, M, G, V, I) or + / –, and the chaining method, which prints in the key."],
        ["Score every step", "in that session's column as the learner works through the task."],
        ["Total the column:", "the number of independent steps and the % independent."],
        ["Graph % independent", "across sessions, or score on screen and it's graphed automatically."],
      ]),
      h2("Single-opportunity or multiple-opportunity assessment"),
      p("To find out which steps a learner can already do, there are two common approaches. In a <strong>single-opportunity</strong> assessment you stop at the first error and score every remaining step as not independent: quick and conservative. In a <strong>multiple-opportunity</strong> assessment you complete the missed step for the learner (or set it up) and keep assessing the rest, which tells you more about later steps. Note which one you used, because they give different percentages."),
    ].join("\n"),
    faq: [
      ["How many steps should a task analysis have?", "As many as the learner needs: a handwashing routine might be 6 steps for one student and 14 for another. The sheet fits about 20 steps on a portrait page and continues onto more pages for longer lists."],
      ["How do I calculate % independent?", "Count the steps completed independently and divide by the number of steps scored. 6 of 8 steps is 75%."],
      ["Can I use + and – instead of prompt levels?", "Yes. Set <em>Score each step with</em> to + / –. + means the step was done independently."],
      ["Which chaining method should I use?", "It depends on the learner and the task, and your BCBA or teaching team should decide. The sheet prints the method in the key so everyone uses the same one."],
    ],
  },

  /* ------------------------------------------------------------------ FREQUENCY */
  {
    slug: "frequency-data-sheet", tool: { kind: "sheet", preset: "frequency" }, crumb: "Frequency data sheet",
    title: "Frequency Data Sheet: Free Tally and Rate Recording Sheet",
    desc: "Free frequency data sheet: tally each occurrence, total it and convert it to a rate per hour or minute. Up to 3 behaviors. Print, PDF or count on a tablet.",
    h1: "Frequency Data Sheet",
    lead: "Tally every time the behavior happens, then turn the count into a rate so sessions of different lengths can be compared. Track up to three behaviors on one sheet.",
    body: [
      quick("Frequency (event) recording counts how many times a behavior happens during an observation. Make one tally mark per occurrence and total them at the end. If observation times vary, convert the count to a rate: count ÷ minutes observed gives a rate per minute, and multiplying by 60 gives a rate per hour. Six call-outs in a 30-minute lesson is 0.2 per minute, or 12 per hour."),
      h2("When frequency recording works best"),
      ul([
        "The behavior has a clear start and end: hitting, hand-raising, calling out, requests, swearing.",
        "Each occurrence is fairly short, so it's obvious when one ends and the next begins.",
        "For behaviors that happen too fast to count or last a long time, use <a href=\"/partial-interval-recording-data-sheet\">interval recording</a> or <a href=\"/duration-recording-data-sheet\">duration recording</a> instead.",
      ]),
      h2("Count or rate?"),
      tbl(["Situation", "What to graph", "Why"], [
        ["Every observation is the same length", "Count per session", "Simple and directly comparable."],
        ["Observation lengths vary", "Rate per minute or per hour", "Removes the effect of longer or shorter observations."],
        ["Several short observations in a day", "Total count ÷ total minutes", "One comparable number per day."],
      ]),
      h2("How to use the sheet"),
      steps([
        ["Name the behaviors", "(up to three) and add an operational definition so everyone counts the same thing."],
        ["Start the row:", "write the date and start time when you begin observing."],
        ["Tally each occurrence", "in that behavior's tally box."],
        ["Close the row:", "write the end time, the total for each behavior and the minutes observed."],
        ["Work out the rate,", "or score on screen with the +1 buttons and the timer, and the rate is calculated and graphed for you."],
      ]),
      h2("Writing a definition two people would agree on"),
      p("A good definition describes what the behavior looks like, not why it happens, and says what counts as one occurrence. For example: <em>Calling out: speaking to the teacher during whole-class instruction without raising a hand and being called on. Each separate statement counts once; repeating the same statement within 3 seconds counts once.</em> With a clear definition, two observers watching the same lesson should get the same count."),
    ].join("\n"),
    faq: [
      ["What's the difference between frequency and rate?", "Frequency usually means the count of occurrences. Rate is the count divided by the observation time, such as 12 per hour. Use rate whenever observation lengths differ."],
      ["How do I count behaviors that come in bursts?", "Decide in advance what separates one occurrence from the next, for example 3 seconds without the behavior, and write it into the definition."],
      ["Can I track more than one behavior?", "Yes, up to three. Each gets its own tally and total columns. On screen, each has its own +1 button and its own line on the graph."],
      ["How do I graph frequency data?", "Label the y-axis with the unit, such as “Responses per hour”, and plot one point per session. On-screen scoring adds the point to the goal's graph automatically."],
    ],
  },

  /* ------------------------------------------------------------------ DURATION */
  {
    slug: "duration-recording-data-sheet", tool: { kind: "sheet", preset: "duration" }, crumb: "Duration recording data sheet",
    title: "Duration Recording Data Sheet: Free Printable + Latency",
    desc: "Free duration recording data sheet: log each episode's start and stop, total duration and % of time observed. Includes a latency sheet. Print or get a PDF.",
    h1: "Duration Recording Data Sheet",
    lead: "Write down how long each episode lasts, total it, and track the percentage of time the behavior took. Switch the type to Latency to time how long a student takes to start.",
    body: [
      quick("Duration recording measures how long a behavior lasts. Note the start and stop time (or the length) of each episode; total duration is the sum of all episodes. To compare sessions of different lengths, use % of time = total duration ÷ time observed × 100. Three tantrums of 1:30, 2:00 and 0:45 during a 30-minute observation add up to 4 minutes 15 seconds, about 14% of the time."),
      h2("When to use duration recording"),
      ul([
        "Behaviors that vary in how long they last: tantrums, crying, time out of seat, time on task.",
        "Goals about how long, not how often: “will remain seated for 10 minutes”.",
        "For very short behaviors, count them instead with a <a href=\"/frequency-data-sheet\">frequency data sheet</a>.",
        "If you can't watch continuously, <a href=\"/momentary-time-sampling-data-sheet\">momentary time sampling</a> gives an estimate of the proportion of time.",
      ]),
      h2("Duration, latency and inter-response time"),
      tbl(["Measure", "Time from…", "Example"], [
        ["Duration", "the start of the behavior to its end", "A tantrum lasted 2 minutes."],
        ["Latency", "the end of an instruction or cue to the start of the response", "Started work 40 seconds after the instruction."],
        ["Inter-response time (IRT)", "the end of one response to the start of the next", "5 minutes between requests for a break."],
      ]),
      h2("How to record duration"),
      steps([
        ["Define the start and the end,", "for example: a tantrum starts when crying begins and ends after 10 seconds of calm."],
        ["Start timing", "with a stopwatch, or note the clock time, when an episode begins."],
        ["Stop at the end", "and write the episode's length (m:ss) or its start and stop times in the next episode box."],
        ["Total the row:", "number of episodes, total duration and minutes observed (and % of time, if you chose it)."],
        ["Graph", "total minutes or % of time. On screen, the Start/Stop button times each episode for you."],
      ]),
      h2("Latency recording"),
      p("Choose <em>Latency</em> in the measurement type menu to get a latency sheet: one row per opportunity, with the time the instruction ended, the time the response began and the difference in seconds. The mean latency per session is what you graph, and the goal is usually to bring it down, for example starting work sooner after an instruction. On screen, tap <em>Instruction given</em>, then <em>Response started</em>, and the latency is recorded."),
    ].join("\n"),
    faq: [
      ["Should I graph total duration or duration per episode?", "Graph total duration (or % of time) when the goal is less time in the behavior overall. If the goal is shorter episodes, divide the total by the number of episodes, which the sheet also records."],
      ["How do I record episodes that run into each other?", "Set an end rule in the definition, such as 10 seconds without the behavior. Anything before that counts as the same episode."],
      ["What observation length should I use?", "Keep it the same each time if you can. If it varies, graph % of time instead of total minutes."],
      ["Is latency the same as response time?", "In behavior analysis, latency is the time from the end of the instruction or cue to the start of the response, not how long the response takes."],
    ],
  },

  /* ------------------------------------------------------------------ PARTIAL */
  {
    slug: "partial-interval-recording-data-sheet", tool: { kind: "sheet", preset: "partial" }, crumb: "Partial interval recording data sheet",
    title: "Partial Interval Recording Data Sheet: Free Printable PDF",
    desc: "Free partial interval recording data sheet: set interval length and observation time, mark intervals where the behavior occurred and get % of intervals. PDF.",
    h1: "Partial Interval Recording Data Sheet",
    lead: "Divide the observation into equal intervals and mark each one in which the behavior happened at all. Choose the interval length and the sheet lays out the grid with times.",
    body: [
      quick("In partial interval recording you split an observation into equal intervals, commonly 10 or 15 seconds, and mark an interval if the behavior happens at any time during it, even once and briefly. The result is the percentage of intervals scored: scored intervals ÷ total intervals × 100. It's an estimate rather than a count, and it tends to overestimate how much of the time the behavior actually happens."),
      h2("How to do partial interval recording"),
      steps([
        ["Choose the interval and observation length.", "10-second intervals for 10 minutes gives 60 intervals. The sheet prints each interval's end time so you can follow a stopwatch."],
        ["Start a timer", "and watch the student for the whole interval."],
        ["Mark the box", "if the behavior happens at any point in the interval. One occurrence is enough; don't mark the same interval twice."],
        ["Count and divide:", "marked intervals ÷ total intervals × 100."],
        ["Graph % of intervals.", "On a tablet, the interval timer highlights the current box and beeps at each change."],
      ]),
      h2("Partial interval vs whole interval vs momentary time sampling"),
      tbl(["Method", "Mark the interval when the behavior…", "Tends to", "Typical use"], [
        ["Partial interval", "happens at any time during the interval", "overestimate", "Behaviors to decrease; brief or frequent behaviors"],
        ["<a href=\"/whole-interval-recording-data-sheet\">Whole interval</a>", "lasts for the entire interval", "underestimate", "Behaviors to increase, such as on-task"],
        ["<a href=\"/momentary-time-sampling-data-sheet\">Momentary time sampling</a>", "is happening at the end of the interval", "over- or underestimate; closer with shorter intervals", "Longer-lasting behaviors; one adult watching several students"],
      ]),
      h2("Choosing the interval length"),
      p("Shorter intervals give a closer estimate but are harder to score while teaching. Many observations use 5 to 15 second intervals with a timer or audio cue. Keep the interval and the observation length the same each session so the percentages can be compared; the sheet prints both in the key."),
      h2("Worked example"),
      p("Off-task behavior was observed for 10 minutes using 10-second intervals, so there were 60 intervals. It occurred during 18 of them: 18 ÷ 60 × 100 = 30% of intervals. That means the behavior happened in 30% of intervals, not that the student was off task for 30% of the time. For the share of time, use <a href=\"/duration-recording-data-sheet\">duration recording</a>."),
    ].join("\n"),
    faq: [
      ["Why does partial interval recording overestimate?", "An interval is scored even if the behavior lasted one second of it, so a short behavior can make a whole interval count. That's why it suits behaviors you want to reduce: it won't make progress look better than it is."],
      ["Can I record more than one behavior?", "Yes, up to three. Each box shows letters (A, B, C) to circle, and the summary line gives a percentage for each behavior."],
      ["What if I miss an interval?", "Mark it as not observed and leave it out of the total. When scoring on screen, lower <em>Intervals observed</em> to match."],
      ["Is partial interval the same as interval recording?", "It's one of three interval-based methods, alongside whole interval recording and momentary time sampling."],
    ],
  },

  /* ------------------------------------------------------------------ WHOLE */
  {
    slug: "whole-interval-recording-data-sheet", tool: { kind: "sheet", preset: "whole" }, crumb: "Whole interval recording data sheet",
    title: "Whole Interval Recording Data Sheet: Free Printable PDF",
    desc: "Free whole interval recording data sheet for behaviors like on-task: mark an interval only if the behavior lasted the whole time and get % of intervals. PDF.",
    h1: "Whole Interval Recording Data Sheet",
    lead: "Mark an interval only when the behavior lasted from start to finish. Ideal for behaviors you want to see more of, such as on-task or engagement.",
    body: [
      quick("In whole interval recording you mark an interval only if the behavior occurred continuously for the entire interval, and report the percentage of intervals scored. Because a brief pause means the interval isn't scored, whole interval recording tends to underestimate how much of the time the behavior happened. That makes it a conservative measure for behaviors you want to increase."),
      h2("When to choose whole interval recording"),
      ul([
        "Behaviors that should last: on-task, engaged, in seat, cooperative play.",
        "The goal is to increase the behavior, so underestimating won't overstate progress.",
        "You can watch the student continuously for each interval. If you can't, consider <a href=\"/momentary-time-sampling-data-sheet\">momentary time sampling</a>.",
      ]),
      h2("How to record"),
      steps([
        ["Define the behavior and what breaks it,", "for example: on-task means eyes on the work or the teacher; looking away for more than 2 seconds ends it."],
        ["Choose the interval and observation length,", "such as 15-second intervals for 15 minutes (60 intervals)."],
        ["Watch each whole interval.", "Mark the box only if the behavior lasted the entire interval; leave it blank at the first break."],
        ["Count and divide:", "marked intervals ÷ intervals observed × 100."],
        ["Graph % of intervals", "for each observation, or score on screen with the interval timer."],
      ]),
      h2("Worked example"),
      p("On-task behavior was observed for 15 minutes with 15-second intervals (60 intervals). The student was on task for the whole of 39 intervals: 39 ÷ 60 × 100 = 65% of intervals. The true share of time on task was probably a little higher, because intervals with a short break weren't counted."),
      h2("Making whole interval data more accurate"),
      ul([
        "Use short intervals, often 5 to 15 seconds. Longer intervals make the underestimate worse.",
        "Write down what counts as a break in the behavior, so every observer ends an interval at the same point.",
        "Keep the interval length the same from session to session.",
        "Check agreement with a second observer now and then: agreeing intervals ÷ total intervals × 100.",
      ]),
      p("For behaviors you want to reduce, <a href=\"/partial-interval-recording-data-sheet\">partial interval recording</a> is the more common choice."),
    ].join("\n"),
    faq: [
      ["What's the difference between whole and partial interval recording?", "Whole interval scores an interval only if the behavior lasted all of it; partial interval scores it if the behavior happened at any point. Whole interval tends to underestimate and partial interval tends to overestimate."],
      ["Why does whole interval recording underestimate?", "A behavior that fills 9 seconds of a 10-second interval still leaves the interval unscored, so time spent in the behavior goes uncounted."],
      ["What interval length should I use?", "Short intervals, commonly 5 to 15 seconds, give a closer estimate. Pick one you can score reliably and keep it the same every time."],
      ["Can I track on-task and off-task together?", "Yes. Add up to three behaviors; each box shows a letter per behavior to circle, with a separate percentage for each."],
    ],
  },

  /* ------------------------------------------------------------------ MTS */
  {
    slug: "momentary-time-sampling-data-sheet", tool: { kind: "sheet", preset: "mts" }, crumb: "Momentary time sampling data sheet",
    title: "Momentary Time Sampling Data Sheet: Free Printable PDF",
    desc: "Free momentary time sampling data sheet: look up at the end of each interval and mark what you see. Set the interval and length, print or use the beep timer.",
    h1: "Momentary Time Sampling Data Sheet",
    lead: "Look at the student only at the end of each interval and mark whether the behavior is happening at that moment. Set the interval, print the grid, or use the beeping timer.",
    body: [
      quick("Momentary time sampling (MTS) records whether a behavior is happening at the exact moment each interval ends, for example every 30 seconds or every minute. Mark the box if the behavior is happening at that instant and leave it blank if not. The result is the percentage of moments scored, an estimate of the share of time the behavior occurs."),
      h2("Why teachers like momentary time sampling"),
      p("You don't have to watch continuously. Glance up when the timer signals, mark the box, and carry on teaching. That makes MTS practical for one adult in a busy classroom and for observing several students in rotation. It works best for behaviors that last a while, such as engagement, on-task, in seat or playing with peers, rather than brief events like hitting, which are easily missed between moments."),
      h2("How to use the sheet"),
      steps([
        ["Choose an interval and an observation length:", "30 seconds for 15 minutes gives 30 moments. Each box shows the moment to look."],
        ["Set a signal:", "a vibrating timer, an interval app, or <em>Score a session on screen</em>, which beeps at each moment."],
        ["Look and mark.", "At each signal, look at the student and mark the box only if the behavior is happening right then."],
        ["Count and divide:", "marked moments ÷ moments observed × 100."],
        ["Graph % of intervals", "for each observation."],
      ]),
      h2("Interval length and accuracy"),
      tbl(["Interval", "Moments in 15 minutes", "Trade-off"], [
        ["10 seconds", "90", "Closest estimate, but hard to keep up while teaching."],
        ["30 seconds", "30", "A practical middle ground for classroom use."],
        ["1 minute", "15", "Easy to do, but brief changes in behavior are easily missed."],
      ]),
      p("Shorter intervals give a closer estimate of the true share of time; longer intervals are easier but rougher. Whatever you choose, keep it the same across sessions."),
      h2("Watching a group: planned activity check"),
      p("A group version, often called planned activity check (PLACHECK), counts how many students are engaged at each moment and records the percentage of the group. To use this sheet that way, write “engaged / present” (for example 5/6) in each box and average the percentages."),
      p("Compare MTS with <a href=\"/partial-interval-recording-data-sheet\">partial interval</a> and <a href=\"/whole-interval-recording-data-sheet\">whole interval</a> recording before choosing a method."),
    ].join("\n"),
    faq: [
      ["Is momentary time sampling a type of interval recording?", "It's usually grouped with interval methods, but you score only the moment each interval ends, not the whole interval."],
      ["Does momentary time sampling over- or underestimate?", "It can do either, depending on how the behavior is spread across the session and how long the intervals are. Shorter intervals reduce the error."],
      ["Can I observe more than one student?", "Yes. Rotate between students at each moment, or make one sheet per student. Up to three behaviors can be scored in each box."],
      ["What if I'm not looking at the moment of the signal?", "Score within a second or two of the signal. If you missed it, mark the moment as not observed and lower the total."],
    ],
  },

  /* ------------------------------------------------------------------ ABC */
  {
    slug: "abc-data-sheet", tool: { kind: "sheet", preset: "abc" }, crumb: "ABC data sheet",
    title: "ABC Data Sheet Printable: Free Checklist and Narrative",
    desc: "Free printable ABC data sheet: record antecedent, behavior and consequence with tick-box checklists or write-in columns, plus possible function. Edit, print.",
    h1: "ABC Data Sheet",
    lead: "Record what happened right before, during and right after each incident. Choose a quick tick-box checklist or open write-in columns, edit the options, and print.",
    body: [
      quick("An ABC data sheet records the <strong>A</strong>ntecedent (what happened just before the behavior), the <strong>B</strong>ehavior (what the student did, described objectively) and the <strong>C</strong>onsequence (what happened right after). Collected over several incidents, ABC data helps a team spot patterns and form a hypothesis about the behavior's function, such as escape, attention, access to items or automatic reinforcement."),
      h2("Checklist or narrative?"),
      tbl(["Layout", "Strengths", "Limits"], [
        ["Checklist (structured)", "Fast to complete; easy to tally patterns; consistent between staff.", "Limited to the listed options, so keep an “Other” line."],
        ["Narrative (open columns)", "Captures details you didn't anticipate.", "Slower to write, harder to summarize, and easier to slip into interpretation."],
      ]),
      p("Many teams start with narrative ABC to learn what typically happens, then build a checklist from those notes. Both layouts are available above, and the antecedent and consequence options are editable."),
      h2("How to fill in an ABC data sheet"),
      steps([
        ["Note when and where:", "the date, time, setting and activity."],
        ["Antecedent:", "what happened just before. A demand, a transition, being told no, attention given to someone else, a loud noise."],
        ["Behavior:", "what the student did, in words anyone could check (“threw the pencil and shouted ‘no’”), with duration and intensity if relevant."],
        ["Consequence:", "what happened right after: what adults and peers did, and what the student got or avoided."],
        ["Possible function:", "a staff hypothesis, to be confirmed by looking at many incidents together."],
      ]),
      h2("Example entry"),
      tbl(["Date & time", "Setting", "Antecedent", "Behavior", "Consequence", "Possible function"], [
        ["9/15 10:05", "Math, whole group", "Worksheet handed out", "Tore the worksheet and put head down for about 2 minutes", "Sent to the calm corner; worksheet not completed", "Escape"],
      ]),
      h2("Common functions of behavior"),
      ul([
        "<strong>Escape or avoidance:</strong> the behavior ends or delays something unpleasant, such as a task.",
        "<strong>Attention:</strong> the behavior gets a reaction from adults or peers, positive or negative.",
        "<strong>Tangible:</strong> the behavior gets access to an item or activity.",
        "<strong>Automatic (sensory):</strong> the behavior is reinforcing in itself, whatever others do.",
      ]),
      h2("Tips"),
      ul([
        "Write it up as soon as possible after the incident.",
        "Describe what you saw and heard, not what you think the student intended.",
        "Collect incidents across different times, activities and staff.",
        "ABC data alone doesn't confirm a function. It's one part of a functional behavior assessment led by a qualified professional.",
      ]),
    ].join("\n"),
    faq: [
      ["What does ABC stand for?", "Antecedent, Behavior, Consequence: what happened before, what the student did, and what happened after."],
      ["How many ABC entries do I need?", "There's no fixed number. Collect enough incidents across different settings and times to see a pattern; your behavior team will say when there's enough."],
      ["Can I change the antecedent and consequence options?", "Yes. In checklist layout, edit the option lists, one per line. They print as tick boxes with an “Other” line."],
      ["Is an ABC chart the same as an FBA?", "No. ABC recording is one descriptive part of a functional behavior assessment (FBA), which also includes interviews, other observations and sometimes a functional analysis."],
    ],
  },

  /* ------------------------------------------------------------------ IEP GRAPH */
  {
    slug: "iep-progress-monitoring-graph", tool: { kind: "graph", preset: "iep" }, crumb: "IEP progress monitoring graph",
    title: "IEP Progress Monitoring Graph Maker: Free, With Aim Line",
    desc: "Free IEP progress monitoring graph maker: plot probe scores by date, draw an aim line to the goal, add a trend line and write a progress note. PNG or PDF.",
    h1: "IEP Progress Monitoring Graph Maker",
    lead: "Plot probe scores on a calendar axis, draw the aim line from baseline to the annual goal, add a trend line, and turn the numbers into a progress note for the report.",
    body: [
      quick("An IEP progress monitoring graph plots a student's scores over time against an aim line that runs from their baseline level to the goal on the goal date. Enter dated scores, set the baseline and the goal, then compare the data and its trend line with the aim line. Several points in a row below the aim line are a signal to review the intervention."),
      h2("How to make an IEP progress monitoring graph"),
      steps([
        ["Collect a baseline.", "Three probes before the intervention starts is common; the aim line starts at their median."],
        ["Use a calendar axis.", "Set the x-axis to <em>Calendar dates</em> so gaps between probes (holidays, absences) are drawn to scale."],
        ["Draw the aim line.", "Turn it on, click <em>Start at the baseline median</em>, then enter the goal value and the goal date, often the annual review."],
        ["Add each probe", "as it's given, weekly or every other week, with its date."],
        ["Add a trend line", "once there are several intervention points, and compare its slope with the aim line."],
        ["Share it.", "Download the PNG for the IEP, or the PDF with the summary table and the progress note."],
      ]),
      h2("Common decision rules"),
      tbl(["Rule", "What you see", "Typical response"], [
        ["Data-point rule", "Several consecutive points (often 4) below the aim line", "Consider changing or intensifying the intervention."],
        ["Data-point rule", "Several consecutive points above the aim line", "Consider raising the goal."],
        ["Trend-line rule", "After enough data (often 6 to 8 points), the trend line is flatter than the aim line", "Consider changing the intervention."],
        ["Trend-line rule", "The trend line is steeper than the aim line", "Consider raising the goal."],
      ]),
      p("Districts and teams use different numbers of points, so write down the rule you follow and apply it the same way for every student."),
      h2("What to measure"),
      p("Progress monitoring works best with short, repeatable measures given the same way each time, such as curriculum-based measures (words correct per minute, digits correct, correct letter sequences), percent accuracy on a fixed probe set, or a structured behavior rating. Keep probe difficulty constant through the year; otherwise a change on the graph may reflect the probe rather than the student. Collect the data with any of the <a href=\"/iep-data-sheet-generator\">printable data sheets</a>."),
      h2("Writing the progress report"),
      p("The progress note under the graph summarizes each phase (mean and range), the trend per week, the average of the last three scores, and where the latest score sits relative to the aim line. It's assembled from fixed templates, not AI, so it states only what the numbers show. Edit it to add context: attendance, changes in instruction, and what the student says about their own progress."),
    ].join("\n"),
    faq: [
      ["How often should IEP goals be progress monitored?", "Follow the schedule in the IEP. Weekly monitoring is common for intensive interventions; every two to four weeks is common otherwise."],
      ["What's the difference between an aim line and a trend line?", "The aim line shows the progress needed to reach the goal on time. The trend line shows the progress actually being made. Comparing their slopes tells you whether the student is on track."],
      ["Can I put more than one goal on a graph?", "One graph per goal is usually clearer. For related measures, such as accuracy and fluency on the same skill, you can add up to three data series."],
      ["Can I share the graph with families?", "Yes. Download the PNG or PDF and add it to the progress report. The data itself stays in your browser."],
    ],
  },

  /* ------------------------------------------------------------------ PHASE CHANGE */
  {
    slug: "phase-change-line-graph", tool: { kind: "graph", preset: "reversal" }, crumb: "Phase change line graph",
    title: "Phase Change Line Graph (ABA): Free Online Graph Maker",
    desc: "Make a phase change line graph for ABA: dashed condition lines, broken data paths and labels for AB, ABAB and changing-criterion designs. Free PNG or PDF.",
    h1: "Phase Change Line Graph Maker",
    lead: "Draw dashed phase-change lines between conditions, break the data path at each change and label every phase. The example below is an ABAB reversal design.",
    body: [
      quick("A phase change line is a vertical dashed line on a single-case line graph, drawn between the last session of one condition and the first session of the next. Data points are not connected across it, and each phase is labeled at the top, for example Baseline and Intervention. Here you add a phase and set its first session; the line, the break in the data path and the label are drawn for you."),
      h2("Rules for phase change lines"),
      ul([
        "Draw the line halfway between two sessions, never through a data point.",
        "Don't connect the data path across the line. Each condition gets its own path.",
        "Label each condition above its phase, using the same words as your write-up.",
        "When a condition repeats, repeat its label (Baseline, FCT, Baseline, FCT) so the reader can see the reversal.",
        "Keep the same y-axis scale across all phases.",
      ]),
      h2("Common single-case designs"),
      tbl(["Design", "Phases", "What the graph needs to show"], [
        ["AB", "Baseline → Intervention", "A change in level or trend after the intervention starts. It's the simplest design but can't rule out other explanations."],
        ["Reversal (ABAB)", "Baseline → Intervention → Baseline → Intervention", "Behavior changes each time the intervention is introduced or withdrawn."],
        ["Changing criterion", "Baseline, then phases with stepwise criteria", "Behavior moves to each new criterion. Name each phase after its criterion."],
        ["Multiple baseline", "The same AB sequence, staggered across behaviors, settings or people", "Change happens in each tier only when the intervention starts there."],
      ]),
      p("GoalTally draws one tier per graph. For a multiple baseline design, make one graph per tier with the same x-axis range and stack them in your document."),
      h2("How to make a phase change line graph"),
      steps([
        ["Enter the sessions", "in order, or paste them from a spreadsheet with a Phase column."],
        ["Add a phase change", "for every condition change and set the session where it starts."],
        ["Name each phase", "with a short label. Long names wrap onto two lines."],
        ["Check the graph:", "the dashed lines sit between sessions and the path breaks at each one."],
        ["Download", "a PNG or a PDF. The PDF can include each phase's mean, range, trend and PND."],
      ]),
      h2("Phase changes in Excel vs here"),
      p("In Excel you split each phase into its own column so the line breaks, then draw the phase line as a shape and add text boxes for the labels (see <a href=\"/aba-graph-template-excel\">ABA graph template for Excel</a>). Here, the break, the dashed line and the label all come from one setting, and they move automatically when you add data."),
    ].join("\n"),
    faq: [
      ["Should phase change lines be dashed or solid?", "Dashed vertical lines are the usual convention for condition changes in ABA graphs, and that's what GoalTally draws."],
      ["Why is the data path broken at a phase change?", "Connecting the last baseline point to the first intervention point would suggest a continuous trend across two different conditions. Breaking the path keeps each condition's data separate for visual analysis."],
      ["Can I make a multiple baseline graph?", "Make one graph per tier (behavior, setting or participant) with the same axis range, then stack the PNGs in your document. Stacked tiers in a single figure aren't supported yet."],
      ["Can a phase have no data yet?", "Yes. A new phase starts with the next session you add, and its line and label appear once it has data."],
    ],
  },

  /* ------------------------------------------------------------------ EXCEL */
  {
    slug: "aba-graph-template-excel", tool: { kind: "graph", preset: "excel" }, crumb: "ABA graph template for Excel",
    title: "ABA Graph Template for Excel: Free CSV + Online Graph Maker",
    desc: "Free ABA graph template for Excel and Google Sheets (CSV), step-by-step Excel graphing steps, or paste your columns here for an instant phase change graph.",
    h1: "ABA Graph Template for Excel",
    lead: "Download a ready-to-fill spreadsheet template, follow the Excel steps for a standard ABA line graph, or skip the formatting and paste your columns into the graph maker below.",
    footnote: "Microsoft Excel and Google Sheets are trademarks of their owners; GoalTally isn't affiliated with Microsoft or Google.",
    body: [
      quick("The quickest way to graph ABA data kept in Excel is to keep it in three columns (Session, Phase, Value), copy them and paste them into the graph maker on this page. Phase-change lines, broken data paths and labels are added automatically. If the graph has to live inside Excel, put each phase in its own column so the line breaks, insert a Line with Markers chart, then add the phase lines and labels by hand."),
      p("<a class=\"btn\" href=\"/aba-graph-template.csv\" download>Download the ABA graph template (CSV)</a> &nbsp;It opens in Excel, Google Sheets and Numbers."),
      h2("Template layout"),
      tbl(["Session", "Date", "Phase", "Percent correct"], [
        ["1", "2026-09-01", "Baseline", "20"],
        ["2", "2026-09-02", "Baseline", "30"],
        ["3", "2026-09-03", "Intervention", "50"],
        ["4", "2026-09-04", "Intervention", "65"],
      ]),
      p("Keep one row per session and type the phase name on every row. Rename the last column to your measure. To graph it, select the cells, copy, and paste them into <em>Paste from Excel or Google Sheets</em> above."),
      h2("How to make an ABA graph in Excel"),
      steps([
        ["Give each phase its own column.", "Session numbers in column A, baseline values in B, intervention values in C, with cells left blank outside each phase. Blank cells are what make Excel break the line between phases."],
        ["Insert the chart.", "Select the data and choose Insert › Line or Area Chart › Line with Markers."],
        ["Clean it up.", "Delete the gridlines and the chart title placeholder, and the legend unless there's more than one data path. Set the y-axis minimum to 0 (and the maximum to 100 for percentages)."],
        ["Draw each phase-change line.", "Insert › Shapes › Line, hold Shift to keep it vertical, place it halfway between the two sessions and set a dashed line style."],
        ["Label the phases and axes.", "Add a text box above each phase and axis titles from the chart elements menu."],
        ["Match the ABA style.", "Make the markers and lines black, then copy the chart into your report."],
      ]),
      p("Menu names vary a little between Excel versions and on a Mac."),
      h2("The catch with Excel graphs"),
      p("Phase-change lines drawn as shapes don't move with the data, so when you add sessions or change the axis you have to move them by hand. A built-in linear trendline fits one whole series, so you need a separate series per phase to get a trend for each phase, and an aim line needs an extra series too. That's why many people keep the data in a spreadsheet but make the graph in a dedicated tool. Here, the <em>CSV</em> button exports your data back out, ready for Excel."),
      h2("Google Sheets"),
      p("The same approach works in Google Sheets: separate columns per phase, then Insert › Chart and choose a line chart, with point size set under the series options. Phase lines can be added with the drawing tool. Or paste the same columns here."),
    ].join("\n"),
    faq: [
      ["Is there a free ABA graph template for Excel?", "Yes. Download the CSV template above. It opens in Excel and Google Sheets with Session, Date, Phase and value columns, and pastes straight into this graph maker."],
      ["Why does Excel connect my baseline and intervention data?", "Because they're in the same column. Excel only breaks a line at blank cells, so put each phase in its own column, or paste the data here, where the break is automatic."],
      ["Can I paste the one-column-per-phase layout here?", "Yes. If every row has a value in only one of the phase columns, the paste importer reads each column as a phase."],
      ["Can I get my data back into Excel?", "Yes. The CSV button downloads Session, Date, Phase and the values, ready to open in Excel."],
    ],
  },

  /* ------------------------------------------------------------------ ABOUT */
  {
    slug: "about", crumb: "About", noRelated: false,
    title: "About GoalTally: Free, Private ABA Graphs and Data Sheets",
    desc: "GoalTally is a free ABA graph maker and data sheet generator from MiniTools. It runs in your browser with no signup, no uploads and no paid tier. Here's why.",
    h1: "About GoalTally",
    lead: "Free graphing and data collection tools for special-education teachers, BCBAs, RBTs, paraprofessionals and students, with no account and nothing uploaded.",
    body: [
      p("GoalTally is part of <strong>MiniTools</strong>, a set of free, single-purpose web tools. It does two connected jobs: it makes printable data sheets matched to how a goal is measured, and it turns session data into a correctly formatted ABA graph with phase-change lines, an aim line, a trend line and a mastery check."),
      h2("Why we built it"),
      p("Data sheets tend to be either fixed PDFs that don't match the goal, or part of a full practice-management platform. Many teachers and BCBA students still build graphs in Excel by hand, redrawing phase lines every time data is added, and AI generators often ask for student details. GoalTally takes a narrower approach: configurable sheets, graphs that follow ABA conventions, and no student information leaving your device."),
      h2("How it works"),
      ul([
        "Everything runs in your browser. Calculations, graphs, sheets and PDFs are made on your device.",
        "Saved goals are kept in your browser's local storage. Encrypted backups are created and opened on your device too.",
        "PDFs are drawn with the open-source jsPDF library, served from this site rather than a third-party CDN.",
        "After your first visit the tools work offline.",
      ]),
      h2("Is it really free?"),
      p("Yes. Every feature is free, with no paid tier and no ads in the tool. Exported graphs and sheets carry a small “Made with GoalTally” credit, which is how other teachers and analysts find it."),
      h2("What it isn't"),
      p("GoalTally isn't a clinical records system and doesn't replace professional judgment. Measurement choices, mastery criteria and treatment decisions belong to the student's team. GoalTally isn't affiliated with any school district, clinic, certification board or software vendor."),
    ].join("\n"),
    faq: [],
    related: [["/", "ABA graph maker"], ["/iep-data-sheet-generator", "IEP data sheet generator"], ["/iep-progress-monitoring-graph", "IEP progress monitoring graph"], ["/privacy", "Privacy & Terms"]],
    relatedTitle: "Start here",
  },

  /* ------------------------------------------------------------------ PRIVACY */
  {
    slug: "privacy", crumb: "Privacy & Terms",
    title: "Privacy Policy & Terms | GoalTally",
    desc: "How GoalTally handles data: graphs, sheets and student initials stay in your browser and are never uploaded. Cookie-free analytics and simple terms of use.",
    h1: "Privacy & Terms",
    lead: "Short version: the data you enter never leaves your device.",
    body: [
      h2("What stays on your device"),
      p("GoalTally runs entirely in your browser. Session data, graphs, data sheet settings, saved goals, recorded sessions and any logo you upload are stored in your browser's local storage on your device. They are never sent to our servers or anyone else's. Clearing your browser data deletes them, so download an encrypted backup if you want to keep them."),
      p("For offline use, the site's own files (pages, scripts and styles) are cached by your browser. Your data isn't part of that cache."),
      h2("Encrypted backups"),
      p("Backups are encrypted on your device with AES-256-GCM, using a key derived from your passphrase with PBKDF2-SHA-256 (310,000 iterations). We never see the file or the passphrase, so we can't recover a lost passphrase."),
      h2("Analytics"),
      p("We use Vercel Web Analytics to count page views and a few anonymous events, such as “a graph was exported as PDF” or “a frequency sheet was downloaded”. It's cookie-free, doesn't track you across sites, and never includes anything you type: no initials, goals, data or file contents."),
      h2("Student information"),
      p("Use initials rather than full names. GoalTally makes no claim of FERPA, HIPAA or other regulatory compliance; how you store devices and printed sheets is governed by your school's or organization's policies."),
      h2("Terms"),
      p("GoalTally is provided “as is”, without warranty. It's a calculation and formatting tool, not clinical or educational advice. You're responsible for the accuracy of the data you enter and the decisions you make with it. GoalTally is free to use for personal, educational and commercial work. Exported graphs and sheets include a small credit line."),
    ].join("\n"),
    faq: [],
    related: [["/", "ABA graph maker"], ["/iep-data-sheet-generator", "IEP data sheet generator"], ["/about", "About GoalTally"]],
    relatedTitle: "Tools",
  },
];
